# Generated by Django 3.1.1 on 2020-09-26 11:12

from django.db import migrations, models
import django.db.models.deletion
import gst_field.modelfields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('website_url', models.URLField()),
                ('GST_status', models.CharField(choices=[('registered_dealer', 'Registered Dealer'), ('unregistered_dealer', 'Unregistered Dealer'), ('compounding_dealer_manufecturer', 'Compounding Dealer Manufecturer'), ('compounding_dealer_foodbusiness', 'Compounding Dealer Foodbusiness'), ('compounding_dealer_others', 'Compounding Dealer others')], max_length=255)),
                ('GSTIN', gst_field.modelfields.GSTField(blank=True, max_length=15, null=True)),
                ('resident_status', models.CharField(choices=[('Resident', 'Resident'), ('Nonresident', 'Nonresident')], max_length=255)),
                ('constitution', models.CharField(choices=[('proprietoryship_individual', 'proprietoryship_individual'), ('limited_liability_firm', 'limited_liability_firm'), ('registed_public_limited_firm', 'registed_public_limited_firm'), ('registed_private_limited_firm', 'registed_private_limited_firm'), ('registred_trust', 'registred_trust'), ('coerative_society', 'coerative_society'), ('a_firm', 'a_firm'), ('hindu_undivided_family', 'hindu_undivided_family'), ('foreign_company', 'foreign_company')], max_length=255)),
                ('income_tax_type', models.CharField(choices=[('Individual', 'Individual'), ('hindu_undivided_family', 'hindu_undivided_family'), ('company', 'company'), ('body_of_individuals', 'body_of_individuals'), ('local_authority', 'local_authority'), ('firm', 'firm'), ('trust', 'trust'), ('association_of_persons', 'association_of_persons'), ('artificial_juridical_person', 'artificial_juridical_person'), ('government', 'government')], max_length=255)),
                ('occupation', models.CharField(choices=[('Individual', 'Individual'), ('hindu_undivided_family', 'hindu_undivided_family'), ('association_of_persons', 'association_of_persons'), ('local_authority', 'local_authority'), ('arbitral_tribunal', 'arbitral_tribunal'), ('government', 'government'), ('partnership_firm', 'partnership_firm'), ('factory_under_FA_1948', 'factory__under_FA_1948'), ('society_under_SA_1860', 'society_under_SA_1860'), ('body_of_individuals', 'body_of_individuals')], max_length=255)),
                ('is_business_entity', models.BooleanField(default=False)),
                ('is_body_corporate', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('office_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('bank_acc_type', models.CharField(choices=[('current_deposits', 'current_deposits'), ('saving_deposits', 'saving_deposits'), ('recurrent_deposits', 'recurrent_deposits'), ('current_deposits', 'current_deposits'), ('fixed_deposits', 'fixed_deposits')], max_length=255)),
                ('benificiary_bank_name', models.CharField(max_length=255)),
                ('benificiary_name', models.CharField(max_length=255)),
                ('acc_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=255)),
                ('IFSC', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('website_url', models.URLField()),
                ('GST_status', models.CharField(choices=[('registered_dealer', 'Registered Dealer'), ('unregistered_dealer', 'Unregistered Dealer'), ('compounding_dealer_manufecturer', 'Compounding Dealer Manufecturer'), ('compounding_dealer_foodbusiness', 'Compounding Dealer Foodbusiness'), ('compounding_dealer_others', 'Compounding Dealer others')], max_length=255)),
                ('GSTIN', gst_field.modelfields.GSTField(blank=True, max_length=15, null=True)),
                ('resident_status', models.CharField(choices=[('Resident', 'Resident'), ('Nonresident', 'Nonresident')], max_length=255)),
                ('constitution', models.CharField(choices=[('proprietoryship_individual', 'proprietoryship_individual'), ('limited_liability_firm', 'limited_liability_firm'), ('registed_public_limited_firm', 'registed_public_limited_firm'), ('registed_private_limited_firm', 'registed_private_limited_firm'), ('registred_trust', 'registred_trust'), ('coerative_society', 'coerative_society'), ('a_firm', 'a_firm'), ('hindu_undivided_family', 'hindu_undivided_family'), ('foreign_company', 'foreign_company')], max_length=255)),
                ('income_tax_type', models.CharField(choices=[('Individual', 'Individual'), ('hindu_undivided_family', 'hindu_undivided_family'), ('company', 'company'), ('body_of_individuals', 'body_of_individuals'), ('local_authority', 'local_authority'), ('firm', 'firm'), ('trust', 'trust'), ('association_of_persons', 'association_of_persons'), ('artificial_juridical_person', 'artificial_juridical_person'), ('government', 'government')], max_length=255)),
                ('occupation', models.CharField(choices=[('Individual', 'Individual'), ('hindu_undivided_family', 'hindu_undivided_family'), ('association_of_persons', 'association_of_persons'), ('local_authority', 'local_authority'), ('arbitral_tribunal', 'arbitral_tribunal'), ('government', 'government'), ('partnership_firm', 'partnership_firm'), ('factory_under_FA_1948', 'factory__under_FA_1948'), ('society_under_SA_1860', 'society_under_SA_1860'), ('body_of_individuals', 'body_of_individuals')], max_length=255)),
                ('is_business_entity', models.BooleanField(default=False)),
                ('is_body_corporate', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('office_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('bank_acc_type', models.CharField(choices=[('current_deposits', 'current_deposits'), ('saving_deposits', 'saving_deposits'), ('recurrent_deposits', 'recurrent_deposits'), ('current_deposits', 'current_deposits'), ('fixed_deposits', 'fixed_deposits')], max_length=255)),
                ('benificiary_bank_name', models.CharField(max_length=255)),
                ('benificiary_name', models.CharField(max_length=255)),
                ('acc_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=255)),
                ('IFSC', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('decs', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('service_cost', models.CharField(max_length=200)),
                ('hsn_code', models.IntegerField()),
                ('hsn_decs', models.TextField()),
                ('IGST', models.IntegerField()),
                ('SGST', models.IntegerField()),
                ('CGST', models.IntegerField()),
                ('service_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
                ('unit_group', models.CharField(max_length=200)),
                ('tax_category', models.CharField(choices=[('Taxable', 'Taxable'), ('NIL rated', 'NIL rated'), ('Exampted', 'Exampted'), ('Non GST', 'Non GST')], max_length=200)),
                ('product_type', models.CharField(choices=[('finished_goods', 'finished_goods'), ('raw_material', 'raw_material'), ('packing_material', 'packing_material'), ('semi_finished_goods', 'semi_finished_goods'), ('trading_goods', 'trading_goods'), ('capital_goods', 'capital_goods')], max_length=200)),
                ('MRP', models.IntegerField()),
                ('is_tax_inclusive', models.BooleanField(default=False)),
                ('is_free_item', models.BooleanField(default=False)),
                ('is_stockable', models.BooleanField(default=True)),
                ('warn_on_negative', models.BooleanField(default=True)),
                ('is_saleable_item', models.BooleanField(default=True)),
                ('include_stock_valuation', models.BooleanField(default=True)),
                ('is_active_product', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('hsn_code', models.IntegerField()),
                ('hsn_decs', models.TextField()),
                ('IGST', models.IntegerField()),
                ('SGST', models.IntegerField()),
                ('CGST', models.IntegerField()),
                ('sale_unit_price', models.FloatField()),
                ('purchase_unit_price', models.FloatField()),
                ('min_sale_qty', models.FloatField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unit')),
            ],
        ),
    ]
