# Generated by Django 3.1.1 on 2020-09-23 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gst_field.modelfields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('office_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, null=True)),
                ('mailing_name', models.CharField(max_length=255, null=True)),
                ('website_url', models.URLField()),
                ('GST_status', models.CharField(choices=[('registered_dealer', 'Registered Dealer'), ('unregistered_dealer', 'Unregistered Dealer'), ('compounding_dealer_manufecturer', 'Compounding Dealer Manufecturer'), ('compounding_dealer_foodbusiness', 'Compounding Dealer Foodbusiness'), ('compounding_dealer_others', 'Compounding Dealer others')], max_length=255)),
                ('PAN', gst_field.modelfields.PANField(max_length=10)),
                ('GSTIN', gst_field.modelfields.GSTField(max_length=15)),
                ('prevyear_annual_turnover', models.IntegerField()),
                ('finance_year', models.CharField(choices=[('JAN-DEC', 'JAN-DEC'), ('APRIL-MARCH', 'APRIL-MARCH')], max_length=255)),
                ('CIN', models.CharField(max_length=21, validators=[django.core.validators.RegexValidator(message='CIN must be Alphanumeric', regex='^([L|U]{1})([0-9]{5})([A-Za-z]{2})([0-9]{4})([A-Za-z]{3})([0-9]{6})$')])),
                ('resident_status', models.CharField(choices=[('Resident', 'Resident'), ('Nonresident', 'Nonresident')], max_length=255)),
                ('constitution', models.CharField(choices=[('proprietoryship_individual', 'proprietoryship_individual'), ('limited_liability_firm', 'limited_liability_firm'), ('registed_public_limited_firm', 'registed_public_limited_firm'), ('registed_private_limited_firm', 'registed_private_limited_firm'), ('registred_trust', 'registred_trust'), ('coerative_society', 'coerative_society'), ('a_firm', 'a_firm'), ('hindu_undivided_family', 'hindu_undivided_family'), ('foreign_company', 'foreign_company')], max_length=255)),
                ('income_tax_type', models.CharField(choices=[('Individual', 'Individual'), ('hindu_undivided_family', 'hindu_undivided_family'), ('company', 'company'), ('body_of_individuals', 'body_of_individuals'), ('local_authority', 'local_authority'), ('firm', 'firm'), ('trust', 'trust'), ('association_of_persons', 'association_of_persons'), ('artificial_juridical_person', 'artificial_juridical_person'), ('government', 'government')], max_length=255)),
                ('occupation', models.CharField(choices=[('Individual', 'Individual'), ('hindu_undivided_family', 'hindu_undivided_family'), ('association_of_persons', 'association_of_persons'), ('local_authority', 'local_authority'), ('arbitral_tribunal', 'arbitral_tribunal'), ('government', 'government'), ('partnership_firm', 'partnership_firm'), ('factory_under_FA_1948', 'factory__under_FA_1948'), ('society_under_SA_1860', 'society_under_SA_1860'), ('body_of_individuals', 'body_of_individuals')], max_length=255)),
                ('is_business_entity', models.BooleanField(default=False)),
                ('is_body_corporate', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(upload_to='')),
                ('PF_number', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='PF must be Alphanumeric', regex='^[A-Z]{2}/\\d{5}/\\d{7}$')])),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('office_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('bank_acc_type', models.CharField(choices=[('current_deposits', 'current_deposits'), ('saving_deposits', 'saving_deposits'), ('recurrent_deposits', 'recurrent_deposits'), ('current_deposits', 'current_deposits'), ('fixed_deposits', 'fixed_deposits')], max_length=255)),
                ('benificiary_bank_name', models.CharField(max_length=255)),
                ('benificiary_name', models.CharField(max_length=255)),
                ('acc_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=255)),
                ('IFSC', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=64)),
                ('location_name', models.CharField(max_length=255)),
                ('GST_reg_status', models.CharField(choices=[('registered_dealer', 'Registered Dealer'), ('unregistered_dealer', 'Unregistered Dealer'), ('compounding_dealer_manufecturer', 'Compounding Dealer Manufecturer'), ('compounding_dealer_foodbusiness', 'Compounding Dealer Foodbusiness'), ('compounding_dealer_others', 'Compounding Dealer others')], max_length=255)),
                ('PAN', gst_field.modelfields.PANField(max_length=10)),
                ('parent_company_GST', models.BooleanField(default=True)),
                ('GST', gst_field.modelfields.GSTField(max_length=15)),
                ('location_id', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('office_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organizations.organization')),
            ],
        ),
    ]
