# Generated by Django 3.1.1 on 2020-09-26 08:41

from django.db import migrations, models
import django.db.models.deletion
import gst_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('user_type', models.CharField(choices=[('Owner', 'Owner'), ('Executive', 'Executive'), ('Employee', 'Employee')], default=None, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('role', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user', models.Model),
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user', models.Model),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('company_name', models.CharField(max_length=50)),
                ('GST', gst_field.modelfields.GSTField(max_length=15)),
                ('PAN', gst_field.modelfields.PANField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user', models.Model),
        ),
    ]
