# Generated by Django 3.1.1 on 2020-09-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='executive',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='executive',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
